- name: Définir les variables d'environnement et alias dans .bashrc pour l'utilisateur
  ansible.builtin.template:
    src: templates/bashrc.j2
    dest: "{{ deploy_home }}/.bashrc"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: '0644'
  become: yes
  when: modif_bashrc | default(true)

