- name: Ajouter les entrées au fichier /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host'] }} {{ host }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    state: present
  when: update_hosts_enabled | default(true)

