- name: rapport des slaves du cluster
  command: hdfs dfsadmin -report
  become: yes
  become_user: hdfs
  register: rapport


- name: Afficher les résultats du rapport
  debug:
    var: rapport.stdout_lines

- name: Vérifier l'espace disque disponible
  command: df -h
  register: disk_space

- name: Afficher les résultats de l'espace disque
  debug:
    var: disk_space.stdout_lines
